### ISSUE TITLE
Duplicate class androidx.navigation.fragment.DialogFragmentNavigator found in modules

### ISSUE THREAD

**Issue by cikichen** [KunMinX/Smooth-Navigation#12]
```
    api 'com.kunminx.arch:smooth-navigation:3.9.0-beta1'
    api("androidx.navigation:navigation-fragment-ktx:$nav_version") {
        exclude group: 'androidx.navigation', module: "navigation-fragment"
   }
```

Duplicate class androidx.navigation.fragment.DialogFragmentNavigator found in modules jetified-smooth-navigation-3.9.0-beta1-runtime (com.kunminx.arch:smooth-navigation:3.9.0-beta1) and navigation-fragment-2.3.5-runtime (androidx.navigation:navigation-fragment:2.3.5)

**Comment by KunMinX** [comment]
无法复现你问题，可先照搬本项目 sample module gradle 的依赖，或检查是否存在额外的 Navigation 依赖
