### ISSUE TITLE
navigation args跨模块传参数的坑能解决吗？

### ISSUE THREAD

**Issue by AweiLoveAndroid** [KunMinX/Smooth-Navigation#19]
mavigation args跨模块传参很头疼。如何更好的封装？

**Comment by KunMinX** [comment]
没懂你的需求哈。
google 封装 navigation 框架，主要侧重于提供可视化预览，在跨模块支持上有所欠缺。
换言之如不是很需要可视化预览，未必需要使用 navigation。
跨模块跳转和通信，建议是使用 ARouter 等专职这类需求的框架。
