### ISSUE TITLE
navArgs()方法不能用

### ISSUE THREAD

**Issue by helloworld10010** [KunMinX/Smooth-Navigation#2]
删掉官方的`androidx.navigation:navigation-fragment`后，获取参数的扩展不能用了，请问咋整
![Dingtalk_20201015173626](https://user-images.githubusercontent.com/20741184/96105801-06529900-0f0d-11eb-905d-a647a0440275.jpg)

**Comment by KunMinX** [comment]
@helloworld10010 
截图无法显示，在 sm.ms 上传吧

**Comment by KunMinX** [comment]
@helloworld10010 

修改一下依赖，将 ktx 依赖中对官方 java 包的依赖排除掉即可：

```groovy
implementation('androidx.navigation:navigation-fragment-ktx:2.3.1') {
        exclude group: 'androidx.navigation', module: "navigation-fragment"
}
implementation 'com.kunminx.archi:smooth-navigation:3.3.2-beta5'
```

**Comment by helloworld10010** [comment]
readme里提到的`androidx.navigation:navigation-fragment` 是java用的，kotlin用户不用在意，直接用 ktx那个exclude版本
