### ISSUE TITLE
launchSingleTop模式跳转页面时，若启动页面时附带了新的arguments，如何处理arguments变更逻辑？

### ISSUE THREAD

**Issue by wonderfulsk** [KunMinX/Smooth-Navigation#21]
launchSingleTop模式跳转页面时，若启动页面时附带了新的arguments，有什么好的方案来处理因arguments变更而需执行的逻辑么？例如页面为文章详情页，启动页面时需附带文章id参数。【一般我会在onCreate时处理数据初始化的逻辑。对文章详情页的case来说就是接收argument中的文章id参数，交给VM来发起文章数据加载。】

测试场景如下：
当前栈顶：AFragment
NavAction: 由AFragment启动AFragment，附带新的arguments，launchSingleTop = true
此时满足栈顶复用条件，"复用"当前栈顶的AFragment示例（这里复用打个引号，原版Navigation实际上未复用实例）

---------方案对比 start------------
-----原版Navigation 行为-------
1. 弹出栈顶AFragment实例
2. 添加新的AFragment实例，arguments赋值为新的arguments

因创建了新实例，因此会执行Fragment onCreate -> onResume一系列生命周期方法，因此可随onCreate使用新的argument完成初始化逻辑。
-----SmoothNavigation行为-------
1. 保持栈顶AFragment实例不变
2. 对该实例调用setArguments方法

因生命周期未变更，除setArguments方法外的任何一个回调方法均不会被执行。
---------方案对比 end------------

在使用SmoothNavigation的情况下，除复写setArguments并处理argument变更逻辑外，有无其他的解决方案？

**Comment by KunMinX** [comment]
没懂你的使用场景哈，
我通常是通过全局 VM 去通知栈顶页面刷新内容，
在遵循响应式编程的模式下，由于页面渲染全都放在观察者中响应和统一操作，所以这个需求很容易实现。

**Comment by wonderfulsk** [comment]
比如“App内的H5的活动落地页”，这类页面自身逻辑是将某个活动url（不同活动的url不一样，因此需通过参数传递的形式来交给页面处理）来交给webView展示。活动页面可在App内任意位置调起。额外的交互要求是不要出现连续多个活动页堆叠的情况，若已经展示了活动页，则在页面上更新，而不要创建新页面覆盖老页面。

总结一下对该页面的需求是：
1. url可由外部设置
2. App任意位置均能调起该页面
3. 若活动页已位于栈顶，则做到“栈顶复用”效果

-----分割线------

我的处理办法是将url作为argument传入，将调起活动页的action定义为globalAction，并设置launchSingleTop=true，在页面生命周期方法内解析argument，给webView赋值。这样就可以实现任意位置均能调起活动页，且栈顶页面可复用。该方案在原生Navigation下是可行的，原生Navigation基于replace的逻辑所开发，对于满足栈顶复用条件的场景，会将栈顶页面先出栈，再创建新的页面覆盖（老页面实例出栈，新页面实例入栈）。

-----分割线-------

而接入smoothNavigation后，我测试发现页面启动的逻辑与原生Navigation是不同的，smoothNavigation并不会“出栈再入栈”，而是仅调用了setArgument将栈顶实例的argument进行了赋值。
在不对现有调起+传参方案做大幅调整的情况下，我调整页面自身逻辑，在setArgument内来进行逻辑判断，完成url的更新，以实现上述的需求。

-----分割线-------

我使用上述"H5活动页"的场景，使用你的方案进行调整，看看你我所想是否一致，以下是调整点：

1. 传参逻辑调整。我的方案将url作为argument传入；你的方案是定义全局VM(SharedViewModel)来持有url(由LiveData等对象持有)，活动页观察该url，以实现url变更后的逻辑（webView.loadUrl）。
2. 页面调起逻辑调整。保持globalAction + launchSingleTop = true不变，在代码内调用navigate的同时，额外对VM的url赋值。（这样就可以做到，若页面不在栈顶，则正常调起页面；若页面已在栈顶，则复用实例，通过对url赋值完成更新）

**Comment by wonderfulsk** [comment]
https://github.com/wonderfulsk/NavigationTestDemo

我创建了一个Demo工程作为上述场景的示范

**Comment by KunMinX** [comment]
是的，该场景下，我通常是以上述代码中 SmoothNavigationDemoActivity 案例提供的方式，来传初值以及后续刷新值，

argument 和 intent 一样，在旋屏重建时得以保留，最初是用于取代直接通过 fragment 构造方法传参的陋习，shareVM 由于生命周期长于 activity，因而旋屏重建时同样得以保留，综合各种因素，我也通常统一使用该方式。

**Comment by wonderfulsk** [comment]
我的目的是对已使用原生Navigation开发的项目做优化，及为新项目开发寻找合适的导航框架，我考虑了一段时间，最终还是打算先使用Navigation官方版本。

我目前找到的所有“Navigation add”类修改版，其栈管理能力均与原生Navigation栈管理有差异（例如本问题的navigate+launchSingleTop，以及navigate 同时 popUpTo），且add与replace模式下fragment切换页面时的Lifecycle state变化不同。这会对已使用原生Navigation的老项目迁移时引入额外的成本及稳定性隐患。

而原生版最大的问题即因replace导致的view重建及重建后的状态恢复会有开销（特指livedata保存的状态回推给view），这个开销与重建的Fragment内view复杂度（及子Fragment）成正相关，较大的开销会导致回退时响应变慢及动画卡顿。我考虑先从优化Fragment加载来解决，等待官方给出更优的解决方案。
