### ISSUE TITLE
结合BottomNavigationView使用有异常

### ISSUE THREAD

**Issue by PeterWu520** [KunMinX/Smooth-Navigation#5]
fragment之间相互重叠，而且每次切换还会重新初始化fragment

**Comment by KunMinX** [comment]
@PeterWu520 

Navigation 的使用场景是，不同层级之间 fragment 的跳转和管理，
同级 fragment 之间请不要使用 Navigation 切换

**Comment by PeterWu520** [comment]
好的，已经改为使用ViewPager2+BottomNavigationView

**Comment by PeterWu520** [comment]
> @PeterWu520
> 
> Navigation 的使用场景是，不同层级之间 fragment 的跳转和管理，
> 同级 fragment 之间请不要使用 Navigation 切换

好的，已经改为使用ViewPager2+BottomNavigationView
