### ISSUE TITLE
页面跳转之后的生命周期问题

### ISSUE THREAD

**Issue by love-311** [KunMinX/Smooth-Navigation#6]
fragment之间跳转画面之后不会走onPause，onStop回调，回到画面不会走onResume等方法~

**Comment by KunMinX** [comment]
@love-311 

smooth-navigation 采用的是 add hide 方式转场，fragment 针对 add hide 的情况设计如此。
如需生命周期节点在特定时机完成任务，可采取以下两种办法：
1.使用官方原本的设计通过 replace 方式跳转
2.在 fragment 的 onHiddenChange 中判断

**Comment by love-311** [comment]
@KunMinX 

感谢解答，感觉nav的设计使用replace或许就是考虑到生命周期的问题，目前看来，的确难以两全的感觉。
