### ISSUE TITLE
fragment 转场时一闪而过上一页的内容

### ISSUE THREAD

**Issue by tiamosu** [KunMinX/Smooth-Navigation#9]
fragment设定app:launchSingleTop="true"时，会出现一闪而过的问题，请问下有啥优化方案么

**Comment by tiamosu** [comment]
> fragment设定app:launchSingleTop="true"时，会出现一闪而过的问题，请问下有啥优化方案么

fragment版本1.3.2

**Comment by KunMinX** [comment]
你想转场不闪的话，可以降到1.2.5

**Comment by tiamosu** [comment]
> 你想转场不闪的话，可以降到1.2.5

我是在当前项目测试的，fragment版本是1.2.5的，还是会一闪而过

**Comment by tiamosu** [comment]
> > 你想转场不闪的话，可以降到1.2.5
> 
> 我是在当前项目测试的，fragment版本是1.2.5的，还是会一闪而过

```xml
 <action
        android:id="@+id/action_to_detailFragment_launchSingTop"
        app:destination="@id/detailFragment"
        app:enterAnim="@anim/h_fragment_enter"
        app:exitAnim="@anim/h_fragment_exit"
        app:launchSingleTop="true"
        app:popEnterAnim="@anim/h_fragment_pop_enter"
        app:popExitAnim="@anim/h_fragment_pop_exit" />
```
在当前DetailFragment继续执行这个action进行跳转的

**Comment by KunMinX** [comment]
那你可以到 google issue 中提个 issue，看看 Jetpack 组的人是怎么看待此事的，

https://issuetracker.google.com/issues
